<div class="value_wpapper">
    <div class="value_title">
        <h4>Why we love it</h4>
    </div>
    <div class="value_block">
        <div class="value_item">
            <div class="value_item_img">
                <img src="<?= $block->getViewFileUrl("images/card/1/4.jpg"); ?>" alt="">
            </div>
            <div class="value_item_title">
                Classic Crew Neck
            </div>
            <div class="value_item_green"></div>
            <div class="value_item_content">
                <p>A must have wardrobe staple that never dates.</p>
            </div>
        </div>
        <div class="value_item">
            <div class="value_item_img">
                <img src="<?= $block->getViewFileUrl("images/card/1/2.jpg"); ?>" alt="">
            </div>
            <div class="value_item_title">
                Exquisitely Crafted Aran Stitches
            </div>
            <div class="value_item_green"></div>
            <div class="value_item_content">
                <p>The classic Honeycomb stitch takes center stage.
                    A tribute to the honeybee and believed to bring the wearer good fortune.</p>
            </div>
        </div>
        <div class="value_item">
            <div class="value_item_img">
                <img src="<?= $block->getViewFileUrl("images/card/1/3.jpg"); ?>" alt="">
            </div>
            <div class="value_item_title">
                Beautifully Soft Merino Yarn
            </div>
            <div class="value_item_green"></div>
            <div class="value_item_content">
                <p>Beautifully crafted from easy to wear merino wool in a range of irresistible colors.</p>
            </div>
        </div>
    </div>

    <div class="value_btn">
        <a href="#" class="button action continue">Get Yours Today</a>
    </div>
    <hr>

</div>
