<div class="contacts">
    <div class="contact-icon">
        <img src="<?= $block->getViewFileUrl("images/phone.svg"); ?>" alt="phone">
    </div>
    <div class="contact">
                    <span class="contact_info">
                        <a href="tel: 1-800-707-5037 ">
                            US 1-800-707-5037
                        </a>
                    </span> <br>
        <span class="contact_info">
                        <a href="tel: +353 1 861 1590 ">
                            INT +353 1 861 1590
                        </a>
                    </span>

    </div>
</div>
