<div class="info_wrapper">
    <div class="info_link">
        <div class="info-link_icon">
            <img src="<?= $block->getViewFileUrl("images/globe.svg"); ?>" alt="globe">
        </div>
        <div class="info_link_text">
            <a href="#">Extended 180 Day Free Returns</a>
        </div>
    </div>

    <div class="select_wrapper">
        <select class="select account">
            <option class="select_list" value="my account">MY ACCOUNT</option>
            <option class="select_list" value="my wish list">MY WISH LIST</option>
            <option class="select_list" value="sign in">SIGN IN</option>
        </select>

        <select class="select currency">
            <option class="select_list" value="aud">AUD (A$)</option>
            <option class="select_list" value="gbp">GBP (&pound;)</option>
            <option class="select_list" value="cad">CAD (CA$)</option>
            <option class="select_list" value="nzd">NZD (NZ$)</option>
            <option class="select_list" value="usd">USD ($)</option>
        </select>
    </div>
</div>
