<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getBaseUrl() . "woman"; ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Women") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <li class="ui-menu-item"><a href="#">New Arrivals</a></li>
        <li class="ui-menu-item"><a href="#">Accessories</a></li>
        <li class="ui-menu-item"><a href="#">Capes & Shawls</a></li>
        <li class="ui-menu-item"><a href="#">Sweaters</a></li>
        <li class="ui-menu-item"><a href="#">Cardigans</a></li>
        <li class="ui-menu-item"><a href="#">T-shirts & Sweatshirts</a></li>
        <li class="ui-menu-item"><a href="#">Hand-Kint Arans</a></li>
    </ul>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getBaseUrl() . "man"; ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Men") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <li class="ui-menu-item"><a href="#">New Arrivals</a></li>
        <li class="ui-menu-item"><a href="#">Accessories</a></li>
        <li class="ui-menu-item"><a href="#">Sweaters</a></li>
        <li class="ui-menu-item"><a href="#">Cardigans</a></li>
        <li class="ui-menu-item"><a href="#">T-shirts & Sweatshirts</a></li>
        <li class="ui-menu-item"><a href="#">Hand-Kint Arans</a></li>
    </ul>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getBaseUrl() . "faq"; ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Kids") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <li class="ui-menu-item"><a href="#">Accessories</a></li>
        <li class="ui-menu-item"><a href="#">Sweaters</a></li>
        <li class="ui-menu-item"><a href="#">T-shirts & Sweatshirts</a></li>
    </ul>
</li>
<li class="level0 level-top ui-menu-item column_2">
    <a href="<?php echo $this->getUrl('custom/index/index'); ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Jewelery") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <div class="submenu_item">
            <span class="title">Department</span>
            <li class="ui-menu-item"><a href="#">New Arrivals</a></li>
            <li class="ui-menu-item"><a href="#">Bracelets & Charms</a></li>
            <li class="ui-menu-item"><a href="#">Brooches</a></li>
            <li class="ui-menu-item"><a href="#">Cufflinks</a></li>
            <li class="ui-menu-item"><a href="#">Earrings</a></li>
            <li class="ui-menu-item"><a href="#">Jewelery Sets & Boxes</a></li>
            <li class="ui-menu-item"><a href="#">Pendants & Necklacas</a></li>
            <li class="ui-menu-item"><a href="#">Religious</a></li>
            <li class="ui-menu-item"><a href="#">Rings</a></li>
            <li class="ui-menu-item"><a href="#">Watches</a></li>
        </div>

        <div class="submenu_item">
            <span class="title">Style</span>
            <li class="ui-menu-item"><a href="#">Claddagh</a></li>
            <li class="ui-menu-item"><a href="#">Connemara</a></li>
            <li class="ui-menu-item"><a href="#">Contemporary</a></li>
            <li class="ui-menu-item"><a href="#">Trinity Knot</a></li>
        </div>
    </ul>
</li>
<li class="level0 level-top ui-menu-item column_2">
    <a href="<?php echo $this->getUrl('custom/index/index'); ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Homeware") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <div class="submenu_item">
            <span class="title">Department</span>
            <li class="ui-menu-item"><a href="#">New Arrivals</a></li>
            <li class="ui-menu-item"><a href="#">Art</a></li>
            <li class="ui-menu-item"><a href="#">Blankets & Throws</a></li>
            <li class="ui-menu-item"><a href="#">Crystal & Glassware</a></li>
            <li class="ui-menu-item"><a href="#">Linen</a></li>
            <li class="ui-menu-item"><a href="#">Ornaments</a></li>
            <li class="ui-menu-item"><a href="#">Pottery</a></li>
            <li class="ui-menu-item"><a href="#">Tableware</a></li>
        </div>

        <div class="submenu_item">
            <span class="title">Irish Brands</span>
            <li class="ui-menu-item"><a href="#">Belleek China</a></li>
            <li class="ui-menu-item"><a href="#">Galway Crystal</a></li>
            <li class="ui-menu-item"><a href="#">Tipperary Crystal</a></li>
            <li class="ui-menu-item"><a href="#">Waterford Crystal</a></li>
        </div>
    </ul>
</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('custom/index/index'); ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Irish Food") ?></span>
    </a>
</li>
<li class="level0 level-top ui-menu-item column_2">
    <a href="<?php echo $this->getUrl('custom/index/index'); ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Irish Gifts") ?></span>
    </a>
    <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all">
        <div class="submenu_item">
            <span class="title">Shop by Recipient</span>
            <li class="ui-menu-item"><a href="#">For Her</a></li>
            <li class="ui-menu-item"><a href="#">For Him</a></li>
            <li class="ui-menu-item"><a href="#">For Girls</a></li>
            <li class="ui-menu-item"><a href="#">For Boys</a></li>
            <li class="ui-menu-item"><a href="#">For Babies</a></li>
            <li class="ui-menu-item"><a href="#">For Dogs</a></li>
        </div>
        <div class="submenu_item">
            <span class="title">Shop by Category</span>
            <li class="ui-menu-item"><a href="#">Authentic Irish Clothing</a></li>
            <li class="ui-menu-item"><a href="#">Homeware</a></li>
            <li class="ui-menu-item"><a href="#">Irish Aran Sweaters</a></li>
            <li class="ui-menu-item"><a href="#">Irish Celtic Jewelery</a></li>
            <li class="ui-menu-item"><a href="#">Our Favorite Gifts</a></li>
            <li class="ui-menu-item"><a href="#">Irish Gifts</a></li>
        </div>

    </ul>

</li>
<li class="level0 level-top ui-menu-item">
    <a href="<?php echo $this->getUrl('custom/index/index'); ?>" class="level-top ui-corner-all" role="menuitem">
        <span><?= __("Clearence") ?></span>
    </a>

</li>
