<div class="footer_location_wrapper">
    <div class="location_item">
        <div class="location_item_header">
            The irish store
        </div>
        <div class="location_item_address">
            Suite 6. <br>
            7 Upper O'Connell Street, <br>
            Dublin 1, ireland
        </div>
    </div>
    <div class="location_item">
        <span>usa/canada:</span> <a href="tel:18007075037">1800 707 5037 (toll free to
            Ireland)</a> <br>
        <span>International:</span> <a href="tel:+35318611590">+353 1 8611590</a> <br>
        <span>Contact us:</span> <a href="mailto:info@theirishstore.com">info@theirishstore.com</a>
    </div>

    <div class="location_item security_block">
        <div class="security">
            <div class="security_text">
                <span>100% secure shopping cart</span>
            </div>
            <div class="security_img">
                <img class="comodo" src="<?= $block->getViewFileUrl("images/comodo-secure.png"); ?>" alt="comodo">
            </div>
        </div>
        <div class="pay_systems">
            <img class="pay_sys" src="<?= $block->getViewFileUrl("images/payment-providers-2.webp"); ?>" alt="pay">
        </div>
    </div>
</div>
