<div class="container">
    <div class="header_container_title">Our top picks</div>
    <div class="slider">
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"> <img
                        src="<?= $block->getViewFileUrl("images/slide_pic_1.jpg"); ?>" alt=""> </a>
                <div class="slidre-item_info-suptitle"><a href="#">Hooded Aran Zipper Coat</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $149.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slide_pic_2.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Valentia Aran Cardigan</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $129.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_3.png"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Cape Clear Aran Dress - NEW</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $109.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_4.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">Connemara Marble Disc Earrings &amp; Pendant Jewelry
                        Set</a></div>
                <div class="slidre-item_price"><span class="_price">$79.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_5.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Lough Dan Aran Cardigan - NEW</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $119.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>

        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"> <img
                        src="<?= $block->getViewFileUrl("images/slide_pic_1.jpg"); ?>" alt=""> </a>
                <div class="slidre-item_info-suptitle"><a href="#">Hooded Aran Zipper Coat</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $149.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slide_pic_2.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Valentia Aran Cardigan</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $129.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_3.png"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Cape Clear Aran Dress - NEW</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $109.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_4.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">Connemara Marble Disc Earrings &amp; Pendant Jewelry
                        Set</a></div>
                <div class="slidre-item_price"><span class="_price">$79.95</span></div>
            </div>
        </div>
        <div class="header_slider-item slider-item">
            <div class="slider-item_info"><a class="slidre-item__info-link" href="#"><img
                        src="<?= $block->getViewFileUrl("images/slider_pic_5.jpg"); ?>" alt=""></a>
                <div class="slider_item_exclusive"><img src="<?= $block->getViewFileUrl("images/exclusive.png"); ?>"
                                                        alt=""></div>
                <div class="slidre-item_info-suptitle "><a href="#">The Lough Dan Aran Cardigan - NEW</a></div>
                <div class="slidre-item_price">Was <span class="old_price"> $119.95</span> Now <span
                        class="current_price"> $99.95</span></div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    ".slider": {
        "customSlider": {}
    }
}
</script>

