 <div class="footer_menu_block social_info">
     <div class="footer_social">
         <div class="social">
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/facebook.svg"); ?>" alt="social"></a></div>
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/pinterest.svg"); ?>" alt="social"></a></div>
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/linkedin.svg"); ?>" alt="social"></a></div>
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/youtube.svg"); ?>" alt="social"></a></div>
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/instagram.svg"); ?>" alt="social"></a></div>
             <div class="social_item"><a href="#"><img src="<?= $block->getViewFileUrl("images/blog.svg"); ?>" alt="social"></a></div>
         </div>
         <div class="footer_menu_text">
             <span>To stay up date with our special offers and greate products</span>
         </div>
     </div>

    <div class="footer_feefo">
        <div class="percent_feefo">
            <span>98%</span>
            <img src="<?= $block->getViewFileUrl("images/feefo.png"); ?>" alt="feefo">
        </div>
        <div class="feefo_title">
            customer satisfaction
        </div>
    </div>
</div>


