    <div class="video-content">
        <div class="video">
            <a href="https://www.youtube.com/embed/rMtA10i-yIU" class="popup fancybox video_bg bg_picture_1">
                <img class = "play_btn" src="<?= $block->getViewFileUrl("images/play.png"); ?>" alt="play">
            </a>

            <div class="video_description">
                <div class="description_title">
                    Traditional Irish Aran Sweaters
                </div>
                <div class="description_text">
                    The finest clothing, homeware and gifts. Perfect to enjoy yourself or give to
                    friends and loved onse.
                </div>
                <div class="video_btn">
                    <a href="#">Shop now</a>
                </div>
            </div>
        </div>
        <div class="video">
            <a href="https://www.youtube.com/embed/BBBfVZsqhrw" class="popup fancybox video_bg bg_picture_2">
                <img class = "play_btn" src="<?= $block->getViewFileUrl("images/play.png"); ?>" alt="play">
            </a>
            <div class="video_description">
                <div class="description_title">
                    Authentic Irish gifts
                </div>
                <div class="description_text">
                    Irish sweetwear and gifts delivered from Ireland. These stunning high-quality crafts
                    products make the perfect gifts for friends and loved once. 180 days free returns
                    and fast shipping to USA.
                </div>
                <div class="video_btn">
                    <a href="#">Shop now</a>
                </div>
            </div>
        </div>
    </div>

<script type="text/x-magento-init">
{
    ".popup": {
        "fancybox": {}
    }
}
</script>
